version: '3.8'

services:
  backend:
    build: ./Backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: on-failure:3
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ripple" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6.2-alpine
    command: redis-server
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ngrok:
    image: wernight/ngrok
    ports:
      - 4040:4040
    env_file:
      - .env
    command: ngrok http backend:8000
    depends_on:
      - backend

  ngrok-frontend:
    image: wernight/ngrok
    ports:
      - 4041:4040
    env_file:
      - .env
    command: ngrok http frontend:3000
    depends_on:
      - frontend

volumes:
  postgres_data:
  redis_data:
