"""rollback gigs

Revision ID: c54fbf2c6763
Revises: fa18d321dfa0
Create Date: 2024-05-27 17:04:09.370106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c54fbf2c6763'
down_revision: Union[str, None] = 'fa18d321dfa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gigs', 'rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=True),
               existing_nullable=True)
    op.drop_column('gigs', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gigs', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('gigs', 'rating',
               existing_type=sa.Float(precision=3, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
