"""added image field to gigs

Revision ID: fa18d321dfa0
Revises: d5c4a4f9d5b5
Create Date: 2024-05-27 16:43:01.654431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa18d321dfa0'
down_revision: Union[str, None] = 'd5c4a4f9d5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gigs', sa.Column('image_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('gigs', 'rating',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3, asdecimal=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gigs', 'rating',
               existing_type=sa.Float(precision=3, asdecimal=True),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('gigs', 'image_filename')
    # ### end Alembic commands ###
